### ISSUE TITLE
Upload builds to GitHub Releases

### ISSUE THREAD

**Issue by NatoBoram** [AdvancedXRay/Auto-Clicker-Fabric#35]
**Is your feature request related to a problem? Please describe.**

At the moment, CurseForge is compromised: https://prismlauncher.org/news/cf-compromised-alert/

This means it's no longer possible to safely download `v1.19.4-1.6.1` until the situation is resolved.

**Describe the solution you'd like**

Uploading a release on GitHub tied to the tag can ensure that the mod is available to non-developers even if CurseForge is down.

This can be done in the GitHub action directly; you can use `gh` in all GitHub actions.

Example: 

```yaml
      - run: gh release create ${{github.ref_name}} --generate-notes --title ${{github.ref_name}} --verify-tag ./build/libs/auto-clicker-fabric-*.jar
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

**Describe alternatives you've considered**

Uploading to Modrinth would be nice, but I doubt their content policy would allow that.

**Additional context**

Absolutely fantastic mod btw.
